#!/usr/bin/env python3
"""Inline local CSS, JavaScript, and referenced assets into one portable HTML file."""

from __future__ import annotations

import argparse
import base64
import mimetypes
import os
import re
import tempfile
from pathlib import Path
from urllib.parse import unquote, urlsplit


ATTRIBUTE_RE = re.compile(
    r"""(?P<name>[a-zA-Z_:][-a-zA-Z0-9_:.]*)\s*=\s*(?P<quote>["'])(?P<value>.*?)(?P=quote)""",
    re.DOTALL,
)
CSS_URL_RE = re.compile(
    r"""url\(\s*(?P<quote>["']?)(?P<value>.*?)(?P=quote)\s*\)""",
    re.IGNORECASE,
)


def attributes(tag: str) -> dict[str, str]:
    return {
        match.group("name").casefold(): match.group("value")
        for match in ATTRIBUTE_RE.finditer(tag)
    }


def local_path(base: Path, value: str, root: Path) -> Path | None:
    stripped = value.strip()
    parsed = urlsplit(stripped)
    if (
        not stripped
        or stripped.startswith("#")
        or parsed.scheme
        or parsed.netloc
        or parsed.path.startswith("/")
    ):
        return None
    candidate = (base / unquote(parsed.path)).resolve()
    try:
        candidate.relative_to(root.resolve())
    except ValueError:
        return None
    return candidate if candidate.is_file() else None


def data_uri(path: Path) -> str:
    mime = mimetypes.guess_type(path.name)[0] or "application/octet-stream"
    encoded = base64.b64encode(path.read_bytes()).decode("ascii")
    return f"data:{mime};base64,{encoded}"


def inline_css_assets(css: str, base: Path, root: Path) -> str:
    def replace(match: re.Match[str]) -> str:
        value = match.group("value")
        asset = local_path(base, value, root)
        return f'url("{data_uri(asset)}")' if asset else match.group(0)

    return CSS_URL_RE.sub(replace, css)


def replace_attribute(tag: str, name: str, value: str) -> str:
    pattern = re.compile(
        rf"""({re.escape(name)}\s*=\s*)(["']).*?\2""",
        re.IGNORECASE | re.DOTALL,
    )
    return pattern.sub(lambda match: f'{match.group(1)}"{value}"', tag, count=1)


def create_single_file_html(entrypoint: Path, destination: Path, root: Path) -> Path:
    entrypoint = entrypoint.resolve()
    root = root.resolve()
    try:
        entrypoint.relative_to(root)
    except ValueError as error:
        raise ValueError("HTML entrypoint must be inside the export root.") from error
    if not entrypoint.is_file():
        raise FileNotFoundError(f"HTML entrypoint is missing: {entrypoint}")

    html = entrypoint.read_text(encoding="utf-8")
    html_base = entrypoint.parent

    def inline_stylesheet(match: re.Match[str]) -> str:
        tag = match.group(0)
        attrs = attributes(tag)
        rel = attrs.get("rel", "").casefold().split()
        stylesheet = local_path(html_base, attrs.get("href", ""), root)
        if "stylesheet" not in rel or stylesheet is None:
            return tag
        css = inline_css_assets(
            stylesheet.read_text(encoding="utf-8"),
            stylesheet.parent,
            root,
        )
        return f"<style data-inlined-from=\"{stylesheet.name}\">\n{css}\n</style>"

    html = re.sub(r"<link\b[^>]*>", inline_stylesheet, html, flags=re.IGNORECASE)

    def inline_script(match: re.Match[str]) -> str:
        opening = match.group("opening")
        attrs = attributes(opening)
        script = local_path(html_base, attrs.get("src", ""), root)
        if script is None:
            return match.group(0)
        code = script.read_text(encoding="utf-8").replace("</script", r"<\/script")
        return f"<script data-inlined-from=\"{script.name}\">\n{code}\n</script>"

    html = re.sub(
        r"(?P<opening><script\b[^>]*\bsrc\s*=\s*[\"'][^\"']+[\"'][^>]*>)"
        r"[\s\S]*?</script\s*>",
        inline_script,
        html,
        flags=re.IGNORECASE,
    )

    def inline_style_block(match: re.Match[str]) -> str:
        return (
            match.group("opening")
            + inline_css_assets(match.group("css"), html_base, root)
            + match.group("closing")
        )

    html = re.sub(
        r"(?P<opening><style\b[^>]*>)(?P<css>[\s\S]*?)(?P<closing></style\s*>)",
        inline_style_block,
        html,
        flags=re.IGNORECASE,
    )

    def inline_asset_tag(match: re.Match[str]) -> str:
        tag = match.group(0)
        attrs = attributes(tag)
        for name in ("src", "poster"):
            asset = local_path(html_base, attrs.get(name, ""), root)
            if asset is not None:
                tag = replace_attribute(tag, name, data_uri(asset))
        return tag

    html = re.sub(
        r"<(?:img|source|video|audio)\b[^>]*>",
        inline_asset_tag,
        html,
        flags=re.IGNORECASE,
    )
    marker = "<!-- Self-contained export generated by AI Product Designer. -->\n"
    html = marker + html

    destination.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        "w", encoding="utf-8", dir=destination.parent, delete=False
    ) as handle:
        handle.write(html)
        temp_path = Path(handle.name)
    os.replace(temp_path, destination)
    return destination


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("entrypoint", type=Path)
    parser.add_argument("destination", type=Path)
    parser.add_argument("--root", type=Path)
    args = parser.parse_args()
    root = args.root or args.entrypoint.resolve().parent
    result = create_single_file_html(args.entrypoint, args.destination, root)
    print(result)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
